### ISSUE TITLE
Results are always erased

### ISSUE THREAD

**Issue by IllidanS4** [WowDevTools/WDBXEditor#10]
Every time I load a Legion DB2 file, the results are loaded in the table, but a second later they are all erased and only the column headers are shown. No errors are displayed, until I try to manipulate the table, then a NullReferenceException is raised in WDBXEditor.Main.NewLine().

**Comment by barncastle** [comment]
What version DB2 files are you using?
Are there any ones this specifically happens on or all?

**Comment by IllidanS4** [comment]
Tried it on 7.1 and 7.3 files. What is interesting though, that it sometimes works and sometimes doesn't. Now I have run it again, on the same files, and they were opened. But after I restarted the program and tried it again, the issue reappeared once more and now I cannot open the files anymore.

**Comment by barncastle** [comment]
I've just published a new release that should resolve this problem. Let me know if it continues.

**Comment by IllidanS4** [comment]
Thanks, now it works perfectly.
