### ISSUE TITLE
ERROR: Strings not found in string table

### ISSUE THREAD

**Issue by m-cavill** [WowDevTools/WDBXEditor#100]
1. I take the ChrClasses.db2 file and open it using WDBXEditor.
2. I change the name of a class from Druid to Testing.
3. I save the file.
4. I re-open the file using WDBX editor and get these errors.

![](https://i.gyazo.com/ed8e34a3e12c2628c5ff477bb08abadc.png)

![](https://i.gyazo.com/999463085dcb45992a3520070bd9c530.png)

**Comment by Luzifix** [comment]
See #99
