### ISSUE TITLE
Error exporting to file One or more errors occurred.

### ISSUE THREAD

**Issue by MichaelPriebe** [WowDevTools/WDBXEditor#11]
When I open a CreatureDisplayInfo.db2, even not editing anything, I get an error trying to save it.

**Comment by barncastle** [comment]
What version client are you currently editing? 
My first thought is that the file is readonly have you tried using Save As?

**Comment by MichaelPriebe** [comment]
Save as is what I was using. Editing 7.2.5.24461 db2 included below.
[creaturedisplayinfo.zip](https://github.com/WowDevTools/WDBXEditor/files/1154278/creaturedisplayinfo.zip)

**Comment by barncastle** [comment]
Not sure what I did last release but this should be resolved in the latest version. Let me know if you encounter this again.
