### ISSUE TITLE
TextureFileData corrupted when trying to edit it

### ISSUE THREAD

**Issue by MichaelPriebe** [WowDevTools/WDBXEditor#12]
Opening TextureFileData, even if you don't change any values, when you export it, the in-game textures are messed up. (The "chest" area of armor does not appear.)

**Comment by barncastle** [comment]
I think I've found a problem with the WDB6 logic. Will look at fixing this tomorrow.

**Comment by barncastle** [comment]
This should be fixed in the latest release. Any problems let me know.
