### ISSUE TITLE
WDBX gives an error on opening multiple files

### ISSUE THREAD

**Issue by skarnproject** [WowDevTools/WDBXEditor#13]
WDBX crashes on navigating between multiple files. Tested on opening GroundEffectTexture.dbc and GroundEfffectDoodad.dbc at the same time. Switching between them causes an error. Wotlk.

**Comment by barncastle** [comment]
Hi Skarn, I've just tested on fresh WotLK files and everything is working fine. Do you have version 1.0.6.a? Also are you getting any form of exception message?

**Comment by barncastle** [comment]
Assuming this is working correctly let me know if not.
