### ISSUE TITLE
Cannot parse definitions for SpellVisualKitModelAttach

### ISSUE THREAD

**Issue by MichaelPriebe** [WowDevTools/WDBXEditor#14]
None of the definitions work so I thought to parse it, but the parsed section never checks once I press parse.

**Comment by barncastle** [comment]
What version of the DB2 are you using?
I've just tried 7.3.0 against the 7.3.0 definitions and 7.2.5 and 7.2.0 against the 7.2.0 definitions and both are parsing correctly.

**Comment by MichaelPriebe** [comment]
Newest version had definitions that worked. (Although they were both labeled as 7.2.0 and the same build?)

**Comment by barncastle** [comment]
Brilliant; glad its working. The second one is actually 7.2.5 if you look inside the xml file it'll have a different build number; naming conventions are based on a major build lookup table that I forgot to update. I'll resolve this next release.
