### ISSUE TITLE
Saving parsed definitions is just bad

### ISSUE THREAD

**Issue by MichaelPriebe** [WowDevTools/WDBXEditor#15]
Clicking save gives no feedback (other than asking you to overwrite it if it exists already)
The build you enter is never used.
Seems to just overwrite whichever pre-installed definitions is closest to it.
Definitions reset to default when you exit the program.

**Comment by barncastle** [comment]
I use this screen for debugging the parser and getting "best guess" definitions and thought there may be merit in leaving it accessible however, from your comments, I think it'll just be better to remove it.
