### ISSUE TITLE
export sql on file on computers outside enUS wrong punkt/comma behavior 

### ISSUE THREAD

**Issue by gpn39f** [WowDevTools/WDBXEditor#16]
if you let windows make translate between single and string, 
then he will take the current locale (deDE) as global command and replace "." with ","
in result the count of columns is wrong in parsed SQL string

in the function ToSQL you can make a additional check for float 

`
  public static string ToSql(this DataRow row)
        {
            StringBuilder sb = new StringBuilder();
            DataColumnCollection cols = row.Table.Columns;

            for (int i = 0; i < cols.Count; i++)
            {
                if (cols[i].DataType.Name.Equals("string", StringComparison.CurrentCultureIgnoreCase)) //Escape formatting
                {
                    string val = row[i].ToString().Replace(@"'", @"\'").Replace(@"""", @"\""");
                    sb.Append("\"" + val + "\",");
                }
                else if (cols[i].DataType.Name.Equals("single", StringComparison.CurrentCultureIgnoreCase))//Escape formatting
                {
                    sb.Append(row[i].ToString().Replace(",", ".") + ",");
                }
                else
                    sb.Append(row[i] + ",");
            }

            return sb.ToString().TrimEnd(',');
        }
`

**Comment by barncastle** [comment]
Thanks for letting me know and for the detailed issue! I've pushed an update to the dev branch and will do a release over the weekend.
