### ISSUE TITLE
6.2.3 bug with SpellXSpellVisual.db2

### ISSUE THREAD

**Issue by Farrarie** [WowDevTools/WDBXEditor#17]
when  I edit SpellXSpellVisual.db2 from 6.2.3
it bugged some of it colunms and it corrupt the db2 file
like  SpellVisual is shown on playercondtion
SpellVisual1 and SpellVisual2 is always 0 and I tried to add you in discord
yet most other db2 I tested work perfectly

**Comment by barncastle** [comment]
Not a problem mate just pushed to the dev branch - looks like I got this definition wildly wrong.
Will do a full release tomorrow evening; I need to sanity check all the work I've done over the weekend first.
