### ISSUE TITLE
New data formats in 7.3 should be supported.

### ISSUE THREAD

**Issue by RaidAndFade** [WowDevTools/WDBXEditor#18]
I haven't done much digging but I've been messing around with a couple of tables and noticed you don't support some things (or don't show it at least).

Take for example the Achievement db in 7.3 (24492). 
There are two anomalies that should be accounted for:
- The ID is a short, not an int. But you force ints. This can be fairly easy if you just cast the short to an int.
- The IconID is now a three byte little endian number. This is definitely harder to handle than the previous one but still should be accounted for.

(Also I think the field count should be Suggested, not enforced. Or at least provide a way to name array elements.)

There's probably many more things that blizz's changed as well but these are things that I've noticed in the past couple of hours.

**Comment by barncastle** [comment]
Thanks for taking the time to look into this. I've had a quick look this morning and it appears that some of the 7.3.0 definitions have changed again. For Achievement the new structure appears to (roughly) be:

```XML
<Table Name="Achievement" Build="24492">
    <Field Name="field00" Type="string" />
    <Field Name="field04" Type="string" />
    <Field Name="field08" Type="uint" />
    <Field Name="field0C" Type="string" />
    <Field Name="field10" Type="ushort" />
    <Field Name="field12" Type="ushort" />
    <Field Name="field14" Type="ushort" />
    <Field Name="field16" Type="ushort" />
    <Field Name="field18" Type="ushort" />
    <Field Name="field1A" Type="byte" />
    <Field Name="field1B" Type="byte" />
    <Field Name="field1C" Type="byte" />
    <Field Name="m_ID" Type="int" IsIndex="true" />
    <Field Name="field1F" Type="int" />
    <Field Name="field22" Type="ushort" />
</Table>
```
I'll have a look at updating these over the coming days.

In regards to array naming conventions; are you suggesting to remove the index from same columns? 
With the current definitions it is already possible to name the arrays; just split them into separate fields i.e.
```XML
<!-- As an array -->
<Field Name="foo" Type="int" ArraySize="2" />

<!-- Split -->
<Field Name="foo" Type="int" />
<Field Name="bar" Type="int" />
```

**Comment by RaidAndFade** [comment]
I'll create a pull request for the structs that I've figured out for 24793 and yeah having the possibility of oddly sized elements would be great to have not only for achievement.db2 but also if you plan on supporting the cache files properly. 

As for arrays unfortunately your suggestion won't work because the tables element lengths are enforced. The program throws an error (for me at least) if there's more columns in my definition than in the file header. So I guess another solution could be to remove that forced limit and allow oversized definitions?

**Comment by barncastle** [comment]
Thanks for the contribution; I'd double check the dev branch as I pushed a new set of definitions over the weekend, some will still be wrong though (e.g. read as an int instead of float) and field names are missing although I try to pair these to what the wiki/Trinity has.

The program already supports uncommon LE numbers see DBReaderExtensions.cs; they've been in use since WDB5. So far I've not had any issues regarding overflows with this method so haven't warranted adding data entry checks.

I didn't think to check that, I'll change the check when I get the chance.

**Comment by RaidAndFade** [comment]
I've looked through the code that reads the XML and the file you mentioned. You do indeed have reading uncommon numbers Implemented in the DBReader but the XML parse has no way to call the DBReader. I would implement this myself but unfortunately I don't usually program in C# 

For 24793 I've figured out and attempted to name (or checked and compared to old data I had) questcache, achievements, items(and the related tables), spells (and related tables), mounts, as well as some other tables. I'll be home in 4 hours or so and like I said I'll commit my PR into it's own XML file around then. 
Most of my structs have names following what my old data was and what your structs for 7.2 and 7.3 contained already, so they're fairly well built.

**Comment by barncastle** [comment]
Thanks for the PR I appreciate the help; I've merged it into the project and will be included in the next release as well as the ability to alias array fields.

In regards to the uncommon numbers; I may look into this in the future (it'd be nice for the DBCache reader to be self contained) however at the moment I feel it is unnecessary. While the structures are technically wrong, the DB2 files contain a table of all field types and offsets which WDBX uses to read and write the correct data.

For anything else just create an issue or poke me on Discord (link is in the readme).
