### ISSUE TITLE
MoP SpellVisualEffectName.db2

### ISSUE THREAD

**Issue by Smerdokryl** [WowDevTools/WDBXEditor#26]
ERROR SpellVisualEffectName.db2 : Definition exceeds record size

[SpellVisualEffectName.zip](https://github.com/WowDevTools/WDBXEditor/files/1648916/SpellVisualEffectName.zip)

**Comment by barncastle** [comment]
I've just published a new build, alternatively you can grab the [updated definition](https://github.com/WowDevTools/WDBXEditor/blob/master/WDBXEditor/Definitions/MoP%205.4.8%20(18414).xml) and drop it in your Definitions folder.
