### ISSUE TITLE
MoP Item-sparse.db2

### ISSUE THREAD

**Issue by Smerdokryl** [WowDevTools/WDBXEditor#27]
There is no definitions for MoP, so I tried Cata and WoD. Both give:

`WARNING Item-sparse.db2 : Strings not found in string table`

[Item-sparse.zip](https://github.com/WowDevTools/WDBXEditor/files/1649817/Item-sparse.zip)

**Comment by barncastle** [comment]
Have just released a new update included in which are a handful of missing MoP definitions.
Any more that you find, just let me know.
