### ISSUE TITLE
CharBaseInfo.dbc MoP (or Cata, or WotLK, or anything else)

### ISSUE THREAD

**Issue by Smerdokryl** [WowDevTools/WDBXEditor#32]
The whole ClassID column is 0s. Also, [according to wowdev.wiki](https://wowdev.wiki/DB/CharBaseInfo), there is no unique id

**Comment by barncastle** [comment]
Using the WoD definition should work for now. It appears that MoP has inline IDs whereas pre-MoP(?) didn't.

**Comment by barncastle** [comment]
Grab the dev definition from [here](https://github.com/WowDevTools/WDBXEditor/blob/dev/WDBXEditor/Definitions/MoP%205.4.8%20(18414).xml) for the time being, I'll do a new release soon once I get a chance to test everything.
