### ISSUE TITLE
wotlk SpellVisualKit.dbc

### ISSUE THREAD

**Issue by ladiszlai** [WowDevTools/WDBXEditor#33]
3.5.5a SpellVisualKit structure does not include "animKitID"  so all of the field values are moved one step left because "animKitID" is originally the "headEffect" .  For example "baseEffect" would be the the "leftHandEffect" : 

![bug](https://user-images.githubusercontent.com/6253595/35767904-9972c222-08f4-11e8-9c2c-8576934e0d56.jpg)

**Comment by barncastle** [comment]
Perfect timing was just working on a release! This has been rolled into the latest version.
