### ISSUE TITLE
MoP CharSections.dbc

### ISSUE THREAD

**Issue by Smerdokryl** [WowDevTools/WDBXEditor#37]
`ERROR CharSections.dbc : Id column contains duplicates.` 

This dbc is from a WoD character models for MoP patch, and it works ingame, but I can't edit it due to the error above

[CharSections.zip](https://github.com/WowDevTools/WDBXEditor/files/1692367/CharSections.zip)

**Comment by barncastle** [comment]
I've had a look and that DBC appears to be pretty broken, if you open it in 010 or MyDbcEditor you'll notice that most of the Ids are 0. The client might be ignoring the Id column or is fixing the Id's upon loading however WDBX purposely doesn't do this... 

FYI the structure never changed between WoD and MoP so in theory you could just copy the WoD variant of this DBC into your MoP client provided the Ids merry-up?
