### ISSUE TITLE
BfA 25902 creaturedisplayinfogeosetdata.db2

### ISSUE THREAD

**Issue by Tamamo-no-Bae** [WowDevTools/WDBXEditor#38]
I am unable to open this db2, instead it gives me a strange error about the Index being located outside the matrix border or something.

**Comment by barncastle** [comment]
Apologies, it looks like I included the relationshipdata column in the definition. If you grab the latest version from [here](https://github.com/WowDevTools/WDBXEditor/blob/dev/WDBXEditor/Definitions/BfA%208.0.1%20(25902).xml) and put it in your definition folder, it should work.
