### ISSUE TITLE
SpellXSpellVisual.db2   Legion 7.3.5

### ISSUE THREAD

**Issue by lululalaland** [WowDevTools/WDBXEditor#42]
Would be nice of you to update the definitions for that db2 file.

**Comment by barncastle** [comment]
What build are you targeting? I've tested against 25875 and it works.

**Comment by lululalaland** [comment]
The current build is 25996 
And you have 25875 ? But isnt the one in the editor 25632 ?
I dont know ... perhaps its just me ...but pre 7.3 it seemed to show the rows differently. My edits just dont seem to work anymore for some reason
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 12.02.18, 21:16, barncastle <notifications@github.com> schrieb:
What build are you targeting? I've tested against 25875 and it works.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/WowDevTools/WDBXEditor","title":"WowDevTools/WDBXEditor","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/WowDevTools/WDBXEditor"}},"updates":{"snippets":[{"icon":"PERSON","message":"@barncastle in #42: What build are you targeting? I've tested against 25875 and it works."}],"action":{"name":"View Issue","url":"https://github.com/WowDevTools/WDBXEditor/issues/42#issuecomment-365048531"}}}

**Comment by barncastle** [comment]
Sorry thought it was a parsing issue, 25875 is the last build this DB changed.

I'll have a look at the weekend.

**Comment by barncastle** [comment]
Thanks for pointing this out - there is a glaring error in my WDC1 implementation. I'll be releasing an update at some point this weekend.

**Comment by barncastle** [comment]
New release should now load and save non-4 byte sparse columns correctly which should resolve your issue.

Have a look and don't hesitate to reopen this issue if you still have problems.
