### ISSUE TITLE
MoP SoundEntries.dbc

### ISSUE THREAD

**Issue by Smerdokryl** [WowDevTools/WDBXEditor#44]
"Strings not found, bla bla bla"

[SoundEntries.zip](https://github.com/WowDevTools/WDBXEditor/files/1720070/SoundEntries.zip)

**Comment by barncastle** [comment]
Looks like I have quite a bit of work to do before I can get the next release out, so right now I'll keep pushing these to the [Dev branch](https://github.com/WowDevTools/WDBXEditor/blob/dev/WDBXEditor/Definitions/MoP%205.4.8%20(18414).xml).

**Comment by barncastle** [comment]
Strings use a StringTable which is essentially a list of <Id, Text>. It just so happens that some of these Ids are both FileDataIds and Ids in the StringTable - if all of them were strings then I'd have probably messed up the definition!
