### ISSUE TITLE
IDs not being refreshed

### ISSUE THREAD

**Issue by Smerdokryl** [WowDevTools/WDBXEditor#45]
If you accidentally create an empty line, then delete it, and after that create a new one, it will have the ID of that empty line + 1, not the same ID as it's supposed to

**Comment by barncastle** [comment]
Primary Keys are controlled by the .Net DataGridView and this "skipping" is a standard AutoIncrement implementation used by most databases. When I get the chance, I'll have a look and see if there is a quick way to override this however I'd rather not go around the houses to do this.

The only problems I can see are for pre-MoP Light* DBs as they require sequential IDs, however these are rarely edited anyway.

**Comment by barncastle** [comment]
I've had a look and there is a lot of faffing around to get this to increment sequentially so I've decided against attempting to change this behaviour.

Obviously if something crops up that is reliant on sequential Ids and is a pain to resolve let me know and I'll look into possible solutions.

Ping me on Discord if you think I've made a bad decision!
