### ISSUE TITLE
Definitions 7.3.5  25632

### ISSUE THREAD

**Issue by Leschen** [WowDevTools/WDBXEditor#46]
CharacterFacialHairstyles
Field Name="ID" Type="int" IsIndex="true" 
Field Name="Geoset" Type="uint" ArraySize="5" 
Field Name="Race" Type="byte" 
Field Name="Sex" Type="byte" 
Field Name="Mesh_ID" Type="byte" /

CharHairGeosets
Field Name="ID" Type="int" IsIndex="true" 
Field Name="RootGeosetID" Type="uint" 
Field Name="Race" Type="byte" 
Field Name="Sex" Type="byte" 
Field Name="CharSection_ID" Type="byte" 
Field Name="Flag" Type="byte" 
Field Name="Expansion" Type="byte" 
Field Name="Field0D" Type="byte" 
Field Name="Field0E" Type="byte" 
Field Name="Field0F" Type="byte" 
Field Name="Field10" Type="byte" 

CharSections
Field Name="ID" Type="int" IsIndex="true" 
Field Name="TextureFileDataID" Type="uint" ArraySize="3" 
Field Name="Flags" Type="ushort" 
Field Name="Race" Type="byte" 
Field Name="Gender" Type="byte" 
Field Name="GenType" Type="byte" 
Field Name="Type" Type="byte" 
Field Name="Color" Type="byte" 

ChrRaces
Field Name="ClientPrefix" Type="string" 
Field Name="ClientFileString" Type="string" 
Field Name="Name" Type="string" 
Field Name="NameFemale" Type="string" 
Field Name="LowercaseName" Type="string" 
Field Name="LowercaseNameFemale" Type="string" 
Field Name="Flags" Type="int" 
Field Name="MaleDisplayID" Type="int" 
Field Name="FemaleDisplayID" Type="int" 
Field Name="CreateScreenFileDataID" Type="int" 
Field Name="SelectScreenFileDataID" Type="int" 
Field Name="MaleCustomizeOffset" Type="float" ArraySize="3" 
Field Name="FemaleCustomizeOffset" Type="float" ArraySize="3" 
Field Name="LowResScreenFileDataID" Type="int" 
Field Name="StartingLevel" Type="int" 
Field Name="UIDisplayOrder" Type="int" 
Field Name="FactionID" Type="ushort" 
Field Name="ResSicknessSpellID" Type="ushort" 
Field Name="SplashSoundID" Type="ushort" 
Field Name="CinematicSequenceID" Type="ushort" 
Field Name="BaseLanguage" Type="byte" 
Field Name="CreatureType" Type="byte" 
Field Name="TeamID" Type="byte" 
Field Name="RaceRelated" Type="byte" 
Field Name="UnalteredVisualRaceID" Type="byte" 
Field Name="CharComponentTextureLayoutID" Type="byte" 
Field Name="DefaultClassID" Type="byte" 
Field Name="NeutralRaceID" Type="byte" 
Field Name="ItemAppearanceFrameRaceID" Type="byte" 
Field Name="CharComponentTexLayoutHiResID" Type="byte" 
Field Name="ID" Type="int" IsIndex="true" 
Field Name="HighResMaleDisplayID" Type="int" 
Field Name="HighResFemaleDisplayID" Type="int" 
Field Name="HeritageArmorAchievementID" Type="int" 
Field Name="MaleCorpseBonesModelFileDataID" Type="int" 
Field Name="FemaleCorpseBonesModelFileDataID" Type="int" 
Field Name="AlteredFormTransitionSpellVisualID" Type="int" ArraySize="3" 
Field Name="AlteredFormTransitionSpellVisualKitID" Type="int" ArraySize="3" 

CreatureDisplayInfo
Field Name="ID" Type="int" IsIndex="true" 
Field Name="CreatureModelScale" Type="float" 
Field Name="ModelID" Type="ushort" 
Field Name="NPCSoundID" Type="ushort" 
Field Name="SizeClass" Type="byte" 
Field Name="Flags" Type="byte" 
Field Name="Gender" Type="byte" 
Field Name="ExtendedDisplayInfoID" Type="uint" 
Field Name="PortraitTextureFileDataID" Type="uint" 
Field Name="CreatureModelAlpha" Type="byte" 
Field Name="SoundID" Type="ushort" 
Field Name="PlayerModelScale" Type="float" 
Field Name="PortraitCreatureDisplayInfoID" Type="int" 
Field Name="BloodID" Type="int" 
Field Name="ParticleColorID" Type="int" 
Field Name="CreatureGeosetData" Type="int" 
Field Name="ObjectEffectPackageID" Type="int" 
Field Name="AnimReplacementSetID" Type="int" 
Field Name="UnarmedWeaponSubclass" Type="int" 
Field Name="StateSpellVisualKitID" Type="int" 
Field Name="InstanceOtherPlayerPetScale" Type="float" 
Field Name="MountSpellVisualKitID" Type="int" 
Field Name="TextureVariation" Type="int" ArraySize="3" 

CreatureDisplayInfoExtra
Field Name="ID" Type="int" IsIndex="true" 
Field Name="FileDataID" Type="int" 
Field Name="HDFileDataID" Type="int" 
Field Name="DisplayRaceID" Type="byte" 
Field Name="DisplaySexID" Type="byte" 
Field Name="DisplayClassID" Type="byte" 
Field Name="SkinID" Type="byte" 
Field Name="FaceID" Type="byte" 
Field Name="HairStyleID" Type="byte" 
Field Name="HairColorID" Type="byte" 
Field Name="FacialHairID" Type="byte" 
Field Name="CustomDisplayOption" Type="byte" ArraySize="3" 
Field Name="Flags" Type="byte" 

CreatureModelData
Field Name="ID" Type="int" IsIndex="true" 
Field Name="ModelScale" Type="float" 
Field Name="FootprintTextureLength" Type="float" 
Field Name="FootprintTextureWidth" Type="float" 
Field Name="FootprintParticleScale" Type="float" 
Field Name="CollisionWidth" Type="float" 
Field Name="CollisionHeight" Type="float" 
Field Name="MountHeight" Type="float" 
Field Name="GeoBoxMin" Type="float" ArraySize="3" 
Field Name="GeoBoxMax" Type="float" ArraySize="3" 
Field Name="WorldEffectScale" Type="float" 
Field Name="AttachedEffectScale" Type="float" 
Field Name="MissileCollisionRadius" Type="float" 
Field Name="MissileCollisionPush" Type="float" 
Field Name="MissileCollisionRaise" Type="float" 
Field Name="OverrideLootEffectScale" Type="float" 
Field Name="OverrideNameScale" Type="float" 
Field Name="OverrideSelectionRadius" Type="float" 
Field Name="TamedPetBaseScale" Type="float" 
Field Name="HoverHeight" Type="float" 
Field Name="Flags" Type="int" 
Field Name="FileDataID" Type="int" 
Field Name="SizeClass" Type="byte" 
Field Name="BloodID" Type="int" 
Field Name="FootprintTextureID" Type="byte" 
Field Name="FoleyMaterialID" Type="byte" 
Field Name="FootstepEffectID" Type="byte" 
Field Name="DeathThudEffectID" Type="byte" 
Field Name="SoundID" Type="int" 
Field Name="CreatureGeosetDataID" Type="int" 

ItemDisplayInfo
Field Name="ID" Type="int" IsIndex="true" 
Field Name="Field01" Type="int" 
Field Name="Field02" Type="int" 
Field Name="ItemVisualID" Type="int" 
Field Name="Field04" Type="int" 
Field Name="Field05" Type="int" 
Field Name="Field06" Type="int" 
Field Name="Field07" Type="int" 
Field Name="Field08" Type="int" 
Field Name="Field09" Type="int" 
Field Name="Field0A" Type="int" 
Field Name="Modelfiledata" Type="int" ArraySize="2" 
Field Name="Texturefiledata" Type="int" ArraySize="2" 
Field Name="Field0D" Type="int" ArraySize="4" 
Field Name="Field0E" Type="int" ArraySize="4" 
Field Name="GeosetFlag" Type="int" ArraySize="2" 

Light
Field Name="ID" Type="int" IsIndex="true" 
Field Name="Pos" Type="float" ArraySize="3" 
Field Name="FalloffStart" Type="float" 
Field Name="FalloffEnd" Type="float" 
Field Name="MapID" Type="ushort" 
Field Name="LightParamsID" Type="ushort" ArraySize="8" 

LightParams
Field Name="Field00" Type="float" 
Field Name="Field04" Type="float" 
Field Name="Field08" Type="float" 
Field Name="Field0C" Type="float" 
Field Name="Field10" Type="float" 
Field Name="Field14" Type="int" ArraySize="3" 
Field Name="LightSkyboxID" Type="ushort" 
Field Name="Field22" Type="byte" 
Field Name="Field23" Type="byte" 
Field Name="Field24" Type="byte" 
Field Name="ID" Type="int" IsIndex="true" 

LightSkybox
Field Name="ID" Type="int" IsIndex="true" 
Field Name="SkyboxPathName" Type="string" 
Field Name="Field2" Type="int" 
Field Name="Field3" Type="int" 
Field Name="Field4" Type="byte" 

NpcModelItemSlotDisplayInfo
Field Name="ID" Type="int" IsIndex="true" 
Field Name="DisplayID" Type="int" 
Field Name="Slot" Type="byte" 

SoundKit
Field Name="ID" Type="int" IsIndex="true" 
Field Name="VolumeFloat" Type="float" 
Field Name="MinDistance" Type="float" 
Field Name="DistanceCutoff" Type="float" 
Field Name="Field04" Type="ushort" 
Field Name="Field05" Type="ushort" 
Field Name="Field06" Type="byte" 
Field Name="Field07" Type="byte" 
Field Name="Field08" Type="byte" 
Field Name="Field09" Type="float" 
Field Name="Field0A" Type="float" 
Field Name="Field0B" Type="float" 
Field Name="Field0C" Type="float" 
Field Name="Field0D" Type="float" 
Field Name="Field0E" Type="float" 
Field Name="Field0F" Type="float" 

SoundKitName
Field Name="ID" Type="int" IsIndex="true" 
Field Name="name" Type="string"

**Comment by barncastle** [comment]
Legend!
