### ISSUE TITLE
Imported data has an Incorrect number of colums

### ISSUE THREAD

**Issue by syphex97** [WowDevTools/WDBXEditor#47]
Whenever i try to import anything this comes up "Import Failed: Imported data has an Incorrect number of colums"

Keeps happening no matter what i try.

**Comment by barncastle** [comment]
WDBX is expecting the SQL table to have the exact same fields and field types as the definition (not necessarily named the same). It was built like this to avoid having to manually map SQL columns to definition fields - which gets out of hand for pre-Cata Spell DBs. 

The intended workflow is:
1. Open the DB in WDBX
2. Export to SQL from WDBX (either via a SQL file or directly)
3. Make changes to the SQL data
4. Import the changed data back into WDBX

Can you attempt to do the above if you're not doing so?
If you are doing the above or get errors still can you let me know what DB and expansion/build you're using please?

**Comment by barncastle** [comment]
It's been a while so I'm hoping that the doing the above has been a success.
If not just reopen this ticket and I'll investigate further.

**Comment by syphex97** [comment]
Hi, my bad, my email was spammed by spam during a while so i seem to have lost the notification from your comment. 

I already tried all of those possible solutions, going back to an old version worked.
The issue at hand seems to be with the new one.

**Comment by barncastle** [comment]
Not a problem!

Can you let me know what DB and expansion/build you're struggling with please? I'll attempt to replicate this.

**Comment by syphex97** [comment]
Client_Version
3.3.5 Wrath of the lich king

Core_Version
TrinityCore rev. 9f334bc6df5b 2017-07-19 14:29:30 +0000 (master branch) (Win64, Release, Static)

core_revision
9f334bc6df5b

Db_version TDB 335.63

Cache ID
63

**Comment by barncastle** [comment]
Thanks! Also, I forgot to ask what DBC you're exporting and subsequently re-importing?

**Comment by syphex97** [comment]
The DBC files is extracted using the Extractors that comes with the revision.

**Comment by barncastle** [comment]
But which one are you trying to edit in WDBX that is causing this issue?

**Comment by syphex97** [comment]
oh i see, i never mentioned what i was trying to do.

Simply i'm trying to import all the custom added ID's from my DB(Item_template) to item.DBC
Using the features that the program offer under 
**Import > From SQL**

**Comment by barncastle** [comment]
Beautiful cheers! 😃 I'll get back to you asap.

**Comment by syphex97** [comment]
The file version of the current one that im using that works is 
**1.0.4.0**

**Comment by barncastle** [comment]
Apologies in the delay in this, I had a manic week last week and have only just gotten around to working on this again.

The **Import > From SQL** is working as I intended i.e. it validates that the datasource has the same column count and types as the definition. This avoids writing a column picker and minimises import issues.

I have however, fixed the **Tools > WotLK Item Import** functionality which is designed exactly for this purpose. It does the same thing as the SQL import however it only imports the applicable columns that map to item.dbc. 

Hopefully this solves your issue, if not, just let me know.
