### ISSUE TITLE
Something went wrong with db2 saving

### ISSUE THREAD

**Issue by deranon** [WowDevTools/WDBXEditor#50]
When opening ItemSparse.db2 for 7.3.5 - everything is fine. After saving, filesize changes even if no changes made and db2 file ingame (replaced serverside) causes different bugs such as missmatching item slots.

**Comment by barncastle** [comment]
I'd not be too mindful of file size differences, while I aim to save a byte-for-byte copy, the modern DB structures (WDB6+) do allow for simplification in saving which I take advantage of in certain scenarios.

In regards to this DB in particular, there is a long standing bug/implementation issue that I've tried to work around, hence the file size difference.

Anyway, there is an issue here and I've spent the weekend working on this. Hopefully sparse table saving is in a better state now (or worse 😄). I'd appreciate it if you could grab the latest [dev build](https://ci.appveyor.com/api/buildjobs/ogq3n7gtvqqqg127/artifacts/WDBXEditor.zip) and trying again for me please? If you could let me know either way, that'd be grand!

**Comment by deranon** [comment]
Problem solved. <3
