### ISSUE TITLE
Can't open ChrRaces with frFR locales

### ISSUE THREAD

**Issue by MrXJKz** [WowDevTools/WDBXEditor#52]
https://i.imgur.com/hkeRux8.png

I've tried to open ChrRaces with frFR locales imsad!

**Comment by barncastle** [comment]
Try the [dev definitions](https://github.com/WowDevTools/WDBXEditor/blob/dev/WDBXEditor/Definitions/Legion%207.3.5%20(25632).xml). I spent the weekend making these 7.3.5 compliant.

If the problem persists let me know!

**Comment by MrXJKz** [comment]
Thanks!
