### ISSUE TITLE
Spell.db2  7.3.5 (25xxx)

### ISSUE THREAD

**Issue by lululalaland** [WowDevTools/WDBXEditor#53]
Cannot be edited. The following error is being shown:

ERROR Spell.db2 : Id column contains duplicates.

Would be nice if you could fix it somehow.

**Comment by barncastle** [comment]
Try the [dev definitions](https://github.com/WowDevTools/WDBXEditor/blob/dev/WDBXEditor/Definitions/Legion%207.3.5%20(25632).xml). I'm overdue a release, I've just not had the time to get one out.
