### ISSUE TITLE
-2E+07 wtf

### ISSUE THREAD

**Issue by MrXJKz** [WowDevTools/WDBXEditor#55]
https://i.imgur.com/PyBR7kp.png

Eh???

**Comment by bloerwald** [comment]
https://en.wikipedia.org/wiki/Scientific_notation

**Comment by barncastle** [comment]
Schlumpf's response is the answer. This is also the default .Net behaviour, which I'm against messing with.

If you need this level of precision there are a bunch of sites (and calculators) that can convert values between notations for you.
