### ISSUE TITLE
Can't use custom

### ISSUE THREAD

**Issue by MrXJKz** [WowDevTools/WDBXEditor#56]
https://transfer.sh/CBkhi/2018-03-13_20-37-49.webm

https://i.imgur.com/Cp0yf9x.png

If we have an id higher than 1048575, WDBX can save (_if we bypass_) but it don't use the ID we've put in it. He maybe use custom added texture with a FileDataID higher than 1048575 and that's why his texture is fucked up in game. 

The last FileDataID from 7.3.5.26124 is 1869802, so higher than 1048575. And there's multiples rows who get a FileDataID higher than that in CreatureModelData.db2... I hope a fix, thanks for your work Barn!

**Comment by bloerwald** [comment]
uh.. 

> if we bypass

You bypass what? A range check? That's "probably" there for a reason. If you remove preconditions, stuff obviously will break. So: What limit did you bypass, and why do you think that's okay?


Your video shows

- currently: 0x625B4
- change to 0x2625B4
- save, load
- value after loading is 0x625B4

`0x2625B4` uses 22 bits (i.e. has the 22th bit set at most). That other issue says something about the column being an `int22`, meaning there only are `21` bits except for the sign available. Does WDBX save `0x1FFFFF`, i.e. the highest `int22` possible? Does the error also happen for `0x200000`?

**Comment by barncastle** [comment]
This one is actually my fault. When I redid the definitions I forgot to recheck the signed flag in the column meta. You can grab the updated [defs from the dev branch](https://github.com/WowDevTools/WDBXEditor/blob/dev/WDBXEditor/Definitions/Legion%207.3.5%20(25632).xml).

Schlumpf has a point though, the validation is there to conform to the limits set by the DB and by bypassing may cause undesired results. Whether using the DB is the right approach is up for debate.

For the record, this column in particular is most likely a uint21. 

Give it a go and let me know!

**Comment by MrXJKz** [comment]
I've tried the definitions from the dev branche, and it's still the same thing sadly. My ID (_2500020_) is still out of range..

**Comment by barncastle** [comment]
Whats the max of a uint21?

**Comment by MrXJKz** [comment]
When I try to import with SQL : "SQL import failed due to incorrect file format.".. The error with min & max value as faded away. ¯\_(ツ)_/¯

**Comment by barncastle** [comment]
I'll have to check later on, I'm at work at the moment I don't have the bits and pieces I need - sorry.

**Comment by MrXJKz** [comment]
No problem bud, I can wait ! :D

**Comment by bloerwald** [comment]
> My ID (2500020) is still out of range...

```
~ $ printf '%x\n' 2500020
2625b4
```

> Whats the max of a uint21?

```
~ $ printf '%x\n' $((2**22-1))
3fffff
```

Have you even tried what I asked you to try, @MrXJKz? i.e., does `0x1FFFFF` work? If yes, but `0x200000` does not, _and the definition is unsigned22_, it is a bug. Otherwise it is just expected.

**Comment by MrXJKz** [comment]
**0x1FFFFF** is working after a save.

**Comment by barncastle** [comment]
Just to clarify this is an **unsigned21** NOT an **unsigned22**. So that would mean the max value is `1FFFFF` not `3FFFFF` (hence my rhetorical question earlier).

The generic error on the SQL import is another matter.

**Comment by MrXJKz** [comment]
**0x200000** return 0 after saving btw

**Comment by bloerwald** [comment]
@MrXJKz If the column can only store 21 bytes, then any value ≥ 2^21 will be cut off, just ignoring all higher bits. `0x200000` is the first value no longer representable with 21 bits, as it *is* 2^21.

@barncastle You should probably throw an exception in bitpacking if `value ≠ (value & ((1 << bits) - 1))` rather than just masking bits away.

**Comment by barncastle** [comment]
Theres evidently an issue here with the validation. Importing from CSV or SQL should throw an error and manually entering invalid numbers should invoke the default datagridview error handler.

At least we've hit the initial problem on the head now.

**Comment by barncastle** [comment]
Validation is working in the latest dev build however I'm going to look into manipulating the Column and Field meta to remove these bitwidth limits on save - stay tuned.

**Comment by MrXJKz** [comment]
Niice!
