### ISSUE TITLE
[Suggestion] Index colums editable

### ISSUE THREAD

**Issue by Kallar12** [WowDevTools/WDBXEditor#59]
As it is now Index couls like ID's cant be edited. But they need to. For example:

Item.db2 colum 1 refernces ItemSparse.db2 colum 1. So these need to be Identical.
I cant edit them. Would be great if you could make those editable.

**Comment by barncastle** [comment]
I'm very hesitant about allowing editable primary keys, this was originally the case and ended up being the biggest support issue I had.

Out of curiosity, how are your IDs getting out of sync? If both records having matching IDs then surely you just add a record to each and the auto-increment will be the same anyway.

You can also insert your own IDs already using *Right Click -> Insert* which then prompts for the new ID and validates if it is unused or not so you can specifically set custom record IDs in both.

**Comment by Kallar12** [comment]
I was trying to leave out an offset so my items start at 735000000. Ill try that insert then.

**Comment by barncastle** [comment]
I'm guessing this achieved the offset you were after? If not, reopen this issue.
