### ISSUE TITLE
ERROR item.db2: Sequence contains no elements

### ISSUE THREAD

**Issue by Pickausrname** [WowDevTools/WDBXEditor#61]
Hi guys, totally new here and my first post, so please excuse me if this is too much of a newb question!

I am trying to open item.db2, it's build 7.3.5, but it gave me the said error in the title.

Can anybody help me with how I can use this tool to extract the contents of this .db2?

Thanks!

The .db2 file is attached as per below:

![error](https://user-images.githubusercontent.com/38211523/38494043-86de991a-3c48-11e8-9477-d78819ddffba.png)

[Item.zip](https://github.com/WowDevTools/WDBXEditor/files/1889505/Item.zip)

**Comment by barncastle** [comment]
Grab the dev build from [here](https://ci.appveyor.com/api/buildjobs/vtkpnj8y9cutc4xs/artifacts/WDBXEditor.zip) and let me know if it works now.

**Comment by Pickausrname** [comment]
Finally had a chance to try it!

The reading and the saving as a CSV part worked. Haven't got a chance to
try the others.

Thanks a bunch :D

**Comment by barncastle** [comment]
Awesome! I've just rolled this into the latest release as well.
For any other problems, just create an issue.
