### ISSUE TITLE
ItemDisplayInfo destroys the Universe

### ISSUE THREAD

**Issue by Smerdokryl** [WowDevTools/WDBXEditor#63]
I edited a couple of boots in ItemDisplayInfo (the db2 comes from 23635, and I'm using the 26654 client), changing Geoset2 to 2. In game, this resulted in literally all geosets ever being disabled, collections disappearing, characters on the login screen having a lightning effect on their hands, and the game freezing forever if you try to log in on one of the characters.

Original: [ItemDisplayInfo.zip](https://github.com/WowDevTools/WDBXEditor/files/2048320/ItemDisplayInfo.zip)

**Comment by Smerdokryl** [comment]
It throws an index out of bounds error

**Comment by barncastle** [comment]
Ignore the previous comment I thought this was a new BfA build.

Something appears to be quite broken. If I get time I'll look at the weekend.

**Comment by barncastle** [comment]
Can you try the latest [dev build](https://ci.appveyor.com/api/buildjobs/8aqvb3wylh7yfyrw/artifacts/WDBXEditor.zip) for me please?

**Comment by Smerdokryl** [comment]
@barncastle It opens the file, but, similarly to the other issue, I feel like there's just too many zeros everywhere

**Comment by barncastle** [comment]
I've compared to 7.2.0.23835 and the values are identical for the rows I compared against. Do you have any exact examples of rows you know are wrong?

**Comment by Smerdokryl** [comment]
Not exact, but this just doesn't look right
![image](https://user-images.githubusercontent.com/35412834/40887869-fb4a4500-6746-11e8-8169-6c52cb6df437.png)

**Comment by barncastle** [comment]
I've checked against WoD 6.2.4+ and all of these records in the screenshot have been 0 filled since then, bar 1330, which was populated in WoD but has since been 0 filled since 7.0.3.

I'd be remiss if I had gotten 4 versions of DB reading wrong - but I guess it is a possibility.

**Comment by Smerdokryl** [comment]
@barncastle It's a possibility, but I doubt it. I'll edit and see what happens

**Comment by Smerdokryl** [comment]
I changed GeosetGroup_2 to 2 at 12341 and now all geosets and collections have disappeared.

The lightning effect isn't there, though

**Comment by Smerdokryl** [comment]
@barncastle It seems I can edit the table now, but I keep getting this weird problem, also with 12341, that I set GeosetGroup_1 to 2, save the table and close it, but when I open it again, that field is back to 0

**Comment by Smerdokryl** [comment]
(In case you're wondering, I do wait for the table to save, not close it instantly)

**Comment by barncastle** [comment]
With the latest dev code I've only managed to replicate this once over the last few days and I'm fairly sure that was user error (as in - I think I opened an unedited file thinking it was the modified one).

My replication steps are:
1. Open the `ItemDisplayInfo` db file you provided
2. Control + G to ID `12341`
3. Set `GeosetGroup_1` to `2`
4. 'Save' or 'Save As'
5. 'Close All'/close WDBX completely
6. Reopen the DB and go to ID `12341` again

Have I missed anything? Is there anything in particular you're doing that I'm not?

**Comment by Smerdokryl** [comment]
I pulled the latest dev build and recompiled.

Doing exactly what you described, the value still is not saved, even though windows recognises that the file has just been edited.

Btw, 'Close All' throws a System.NullReferenceException

**Comment by Smerdokryl** [comment]
It appears, the problem was caused by having CASCHost run while I'm editing the file (which is in the Data folder of CASCHost). I did not expect that, because I thought, once 'compiled', it only interacts with the Output folder, unless I do Rebuild

**Comment by barncastle** [comment]
Strange - either something isn't being killed properly in CASCHost or Windows is keeping the file open for whatever reason.

Does this mean, from a WDBX perspective, everything is working correctly now?

**Comment by Smerdokryl** [comment]
Yes, it does
(except the value of 2 seems to have no visible effect, i.e. does not activate the 'mini skirt' geoset, but I think that's not a WDBX problem)

**Comment by barncastle** [comment]
Sounds like this is resolved as for WDBX at the moment. Obviously if that geoset does exist and work but not with edits from WDBX - let me know.
