### ISSUE TITLE
Help docs are showing up empty

### ISSUE THREAD

**Issue by dkpminus** [WowDevTools/WDBXEditor#64]
![wdbx editor help](https://user-images.githubusercontent.com/17548991/40880827-bdaa0e66-667d-11e8-8525-eec7c83db0eb.JPG)

**Comment by barncastle** [comment]
Strange, I've tried this on several PCs and it is fine. A quick Google indicates that the file might be "blocked". Try to right-click on the `Help.chm` file and select Properties, if you see an "Unblock" button, click on it and try again. ([Reference](https://stackoverflow.com/questions/4400744/chm-viewer-unable-to-show-contents))

If none of that works, reopen this, I'll convert it to another format for you.
