### ISSUE TITLE
WDC1 RelationShipData not showing correct value for spellmisc.db2

### ISSUE THREAD

**Issue by alishahb** [WowDevTools/WDBXEditor#65]
**RelationShipData** column not showing correct value for table _spellmisc.db2_
![default](https://user-images.githubusercontent.com/8345328/40883446-d22f2424-6705-11e8-8181-7f251d978ab5.png)

There should be corresponding _SpellId_ value for this table, similar as in spellcategories.db2 (which do show correct SpellId value in RelationShipData column).

[spellmisc.zip](https://github.com/WowDevTools/WDBXEditor/files/2065690/spellmisc.zip)

^ attached spellmisc.db2

**Comment by alishahb** [comment]
It do however read them correctly here

![default](https://user-images.githubusercontent.com/8345328/40883540-2e30bbb4-6708-11e8-8b5a-e9b4fea99033.png)


**Output:**
SpellId: 1			index: 0
SpellId: 3			index: 1
SpellId: 4			index: 2
SpellId: 5			index: 3
SpellId: 7			index: 4
SpellId: 11			index: 5
SpellId: 13			index: 6
....
SpellId: 263099			index: 180217
SpellId: 263101			index: 180218
SpellId: 263113			index: 180219
SpellId: 263159			index: 180220
SpellId: 263166			index: 180221


[readOutput.txt](https://github.com/WowDevTools/WDBXEditor/files/2065698/readOutput.txt)

_but do not show correctly in results_

**Comment by barncastle** [comment]
Thanks for the detailed issue. It looks like the code generating the final data was incorrect for PalletArrays. Can you try the latest [dev build](https://ci.appveyor.com/api/buildjobs/8aqvb3wylh7yfyrw/artifacts/WDBXEditor.zip) for me please?

**Comment by Smerdokryl** [comment]
@barncastle I had a similar issue with SpellXSpellVisual.db2 and, following Marlamin's suggestion, tried using the dev branch, which helped!

However, even with the dev branch, something like that happens to SpellVisual.db2: it's almost completely empty (zeros)

**Comment by barncastle** [comment]
@Smerdokryl I had some bad math that broke `SpellVisual.db2`.

**Comment by Smerdokryl** [comment]
@barncastle SpellVisual.db2 appears to be working now!

**Comment by alishahb** [comment]
@barncastle working correctly now, thank you for fast fix! <3

**Comment by barncastle** [comment]
Awesome! Closing this now, just reopen if the issue reoccurs.
