### ISSUE TITLE
SpellVisual.db2 and SpellVisualKit.db2 7.3.5 26654

### ISSUE THREAD

**Issue by Ulduar** [WowDevTools/WDBXEditor#66]
Structure not defined for this table in Editor.
For SpellVisual.db2 structure can be founded in https://github.com/TrinityCore/TrinityCore/issues/22002#issue-329357603

For SpellVisualKit.db2 i don't know, sorry.

**Comment by WainPetopia** [comment]
Same with creaturefamily.db2

**Comment by barncastle** [comment]
What do you mean by *not defined*? As in missing from the 7.3.5 definitions, missing field names or this is the error message produced upon loading these files?

**Comment by WainPetopia** [comment]
That's the error message that the application gives. For creaturefamily.db2 it says:

> ERROR creaturefamily.db2 : Index was outside the bounds of the array

creaturefamily is smaller in the new build so I'm guessing they deleted or compressed a column or two. I'm happy to try to work out what's going on. Is there an easy way of determining what changed, or just trial and error?

**Comment by Ulduar** [comment]
``` CPP
What do you mean by not defined? As in missing from the 7.3.5 definitions, missing field names or this is the error message produced upon loading these files?
```
Missing Field Names, also i cannot see other SpellVisual for this Visual. 

Example, 70315 visual id for spell id 252729 (Cosmic Ray).
I cannot see CasterVisualId and TargetVisualId.

Example in SQL:
```CPP
CREATE TABLE `db_Spellvisual_25632` ( `ID` INT NOT NULL DEFAULT '0', `Field1_1` FLOAT NOT NULL DEFAULT '0', `Field1_2` FLOAT NOT NULL DEFAULT '0', `Field1_3` FLOAT NOT NULL DEFAULT '0', `Field2_1` FLOAT NOT NULL DEFAULT '0', `Field2_2` FLOAT NOT NULL DEFAULT '0', `Field2_3` FLOAT NOT NULL DEFAULT '0', `Field3` INT NOT NULL DEFAULT '0', `Field4` SMALLINT UNSIGNED NOT NULL DEFAULT '0', `Field5` TINYINT UNSIGNED NOT NULL DEFAULT '0', `Field6` TINYINT UNSIGNED NOT NULL DEFAULT '0', `Field7` INT NOT NULL DEFAULT '0', `Field8` INT NOT NULL DEFAULT '0', `Field9` INT NOT NULL DEFAULT '0', `FieldA` INT NOT NULL DEFAULT '0', `FieldB` INT NOT NULL DEFAULT '0', `FieldC` INT NOT NULL DEFAULT '0', `FieldD` INT NOT NULL DEFAULT '0', `FieldE` INT NOT NULL DEFAULT '0', PRIMARY KEY (`ID`)) ENGINE=MyISAM DEFAULT CHARSET=utf8;
```

```SQL
INSERT INTO `db_Spellvisual_25632` VALUES (70315,0,0,0,0,0,0,0,0,34,255,0,0,0,0,0,0,0,0); 
```



``` CPP
Same with creaturefamily.db2
```
No, creaturefamily.db2 have defined field name and load without error.

**Comment by barncastle** [comment]
@WainPetopia Apologies, I've been slacking on this project of late, I've just pushed the 26654 defs to the dev branch - you can get the [build here](https://ci.appveyor.com/api/buildjobs/171onn4wqkrsc4ts/artifacts/WDBXEditor.zip). I'll publish a release once I get these two issues closed.

@Ulduar The above applies as well - all fields are named too. I've had a look and the values above appear to be correct for ID 70315, should `CasterVisualId` and `TargetVisualId` (aka `CasterSpellVisualID` and `HostileSpellVisualID`) be populated with a non-zero value? If so, do you know what?

**Comment by Ulduar** [comment]
@barncastle 
If they are filled correctly, which stores CasterSpellVisualID and HostileSpellVisualID?

``` CPP
If so, do you know what?
```
Sorry, i don't know, I was guided by the link from the problem in another issue.

**Comment by WainPetopia** [comment]
@barncastle : no need to apologize, I really appreciate your work, and thanks for pushing a new build! :)

**Comment by WainPetopia** [comment]
@barncastle - I tried the new build but it gives the same error. Also, the 26654 build is listed as Legion instead of BfA, though I assume that's not the problem.

**Comment by WainPetopia** [comment]
Ah, it's because there's a later build than 26654. The columns have been rearranged in the most recent one, 26806, like:
https://github.com/Arctium/ClientDB-Structures/blob/master/Structures/CreatureFamily.lal
I guess this will apply to other DBs too.

**Comment by barncastle** [comment]
@Ulduar I've looked again and checked with other readers and this does appear to be returning the right values. For reference `FieldC` is `HostileSpellVisualID` and `FieldD` is `CasterSpellVisualID` on the current definition. 

@WainPetopia For 26654 this should be correct. For 8.0.1.26806 - you're right, they moved almost every field of every DB around which has caused some royal headaches. Does that mean you need the latest BfA structures instead?

**Comment by WainPetopia** [comment]
@barncastle it's not urgent as I'm only interested in a subset and I can make my own defs now I've worked out what's going on :)

**Comment by Ulduar** [comment]
@barncastle thanks for check!

**Comment by Ulduar** [comment]
@barncastle, please, you can upload new release? Thanks advance!

**Comment by barncastle** [comment]
Hey both, yeah sorry, motivation issues and/or life stopped me in my tracks. Latest build has the defs discussed here and the latest BfA ones. Once I move to DBD these will be automated!

**Comment by Ulduar** [comment]
Big thanks)
