### ISSUE TITLE
Failed version check at startup

### ISSUE THREAD

**Issue by WainPetopia** [WowDevTools/WDBXEditor#67]
Just a suggestion, but WDBX editor takes a very long time to load because of a version check, which always times out:
![wdbxversioncheck](https://user-images.githubusercontent.com/25504585/41201843-1d3955fe-6d03-11e8-9a0d-a26ea0b14724.JPG)

Because it takes so long to do this, and there's no splash screen, a new user would get the impression that it's failing to load at all, rather than just taking a long time. Is there any way you can indicate to the user that it's version checking? Or perhaps leave this until a later stage? :)

This is such a useful program, by the way, thank you :)

**Comment by barncastle** [comment]
Looks like the wrong Git API was being used and was returning all releases (which is direly slow) not just the latest. The check also asynchronous now so it doesn't halt the application upon load - if the update popup appears too randomly let me know. 

I'll release this shortly after looking at the other issues.

**Comment by WainPetopia** [comment]
Thank you :)
