### ISSUE TITLE
update definitions for Bfa beta 27075

### ISSUE THREAD

**Issue by alishahb** [WowDevTools/WDBXEditor#68]
_Can you please update definitions for Bfa beta 27026_

Attaching example of db which do not parse, as table structure changed i guess.
It is talent.db2 (all data for this build exists in CASCExplorer)
[talent.zip](https://github.com/WowDevTools/WDBXEditor/files/2192109/talent.zip)

![image](https://user-images.githubusercontent.com/8345328/42684515-f4b6ca1c-8698-11e8-85e0-0712837fc232.png)

**Comment by alishahb** [comment]
Same with table itemeffect.db2, attaching it
[itemeffect.zip](https://github.com/WowDevTools/WDBXEditor/files/2192138/itemeffect.zip)

**Comment by alishahb** [comment]
Same with table spellcasttimes.db2, attaching it
[spellcasttimes.zip](https://github.com/WowDevTools/WDBXEditor/files/2192152/spellcasttimes.zip)

**Comment by barncastle** [comment]
Latest build has the definitions for  8.0.1.27075 which is the latest build, hopefully these will work for 27026 too. Let me know if not!

**Comment by alishahb** [comment]
found one not working table in 27075
![image](https://user-images.githubusercontent.com/8345328/42778217-0edf9154-8945-11e8-8152-7a2036726309.png)
[talent.zip](https://github.com/WowDevTools/WDBXEditor/files/2199010/talent.zip)

**Comment by barncastle** [comment]
Sorry, messed this one up. The structure should be:

```
<Table Name="PvpTalent" Build="27075">
	<Field Name="Description_Lang" Type="string" />
	<Field Name="ID" Type="int" IsIndex="true" />
	<Field Name="SpecId" Type="int" />
	<Field Name="SpellID" Type="int" />
	<Field Name="OverridesSpellID" Type="int" />
	<Field Name="Flags" Type="int" />
	<Field Name="ActionBarSpellID" Type="int" />
	<Field Name="PvpTalentCategoryID" Type="int" />
	<Field Name="LevelRequired" Type="int" />
</Table>
```

Alternatively, swap out the 27026 definition with the one from the [dev branch](https://github.com/WowDevTools/WDBXEditor/blob/dev/WDBXEditor/Definitions/BfA%208.0.1%20(27075).xml).
