### ISSUE TITLE
Out of bounds error in ArtifactPower.db2 - Legion 26XXX

### ISSUE THREAD

**Issue by Darkon47** [WowDevTools/WDBXEditor#70]
As the title states, trying to open artifactPower.db2 from 7.3.5 (26822) results in an out of bounds error.

**Comment by barncastle** [comment]
I've dumped the definitions from the final Legion build which should be near enough identical to 26822. 

If you grab them from [here](https://github.com/WowDevTools/WDBXEditor/blob/dev/WDBXEditor/Definitions/Legion%207.3.5%20(26972).xml) and put them in your `Definitions` folder you should be good to go. I'll also probably do another release by the end of the week with these included.
