### ISSUE TITLE
7.3.5 Legion SpellVisual.db2 and GameObjectDisplay.db2

### ISSUE THREAD

**Issue by Ulduar** [WowDevTools/WDBXEditor#73]
Hello. I have questions. How find soundId for spells.
Search in SpellVisual.db2 not display soundid (zero values)
http://ru.wowhead.com/sound=79481/spell-karazhan-timewarp-cast

INSERT INTO `db_SoundKitName_26654` VALUES (79481,"SPELL_Karazhan_TimeWarp_Cast");

Also i cannot find gameobject display for KarazhanChessDoor.
(79480,"GO_KarazhanB_ChessDoor01");
http://ru.wowhead.com/sound=79480/go-karazhanb-chessdoor01
Thanks Advance.

**Comment by barncastle** [comment]
Unfortunately I'm not the best person to ask. I'd suggest asking in one of the modding communities:
- [WoWDev discord](https://discord.gg/EzKJjtv)
- [modcraft](http://modcraft.io)
- [MC.net](http://model-changing.net)

**Comment by Ulduar** [comment]
Sorry and thanks for link.

**Comment by Ulduar** [comment]
![default](https://user-images.githubusercontent.com/18075953/43050598-2ba8369e-8e25-11e8-819a-9a6e5ec594ef.png)
Hello @barncastle 
That's what I meant. I incorrectly put it
