### ISSUE TITLE
Does this support 'Product.db' Launcher Files?

### ISSUE THREAD

**Issue by LuxInno** [WowDevTools/WDBXEditor#74]
As the title states I was wondering if this supports the .product.db and product.db that can be found in a game's installation directory and in the Blizzard launcher directory inside of ProgramData?

If not do these files look like they could be one of these formats and would just need a little adaptation or is it something else?

**Comment by barncastle** [comment]
I'm currently on holiday, on my phone, so this will be short and sweet and probably incorrect so apologies in advance. Off the top of my head:

- These files aren't supported and won't easily be. They're battle.net specific cache files, unrelated to the WoW DB files and don't use any variant of the WoW DB formats
- These files are, as far as I'm aware, currently undocumented
- Last time I checked, while these are a binary format, a good amount of the data is stored as strings; so opening in notepad might suffice for your needs

If you follow the discord link in the readme I'm sure someone there can provide more information for you.
