### ISSUE TITLE
WDC3 support

### ISSUE THREAD

**Issue by WainPetopia** [WowDevTools/WDBXEditor#79]
Are you planning to update the tools for WDC3? Currently they won't open databases from the PTR. 
https://wowdev.wiki/DB2#WDC3

Thanks again for all your work :)

**Comment by IrcDirk** [comment]
Yes, this wonderfull program needs an update for WDC3 becouse 8.1 is live and cant open any databases :(

**Comment by greenonion0** [comment]
https://bnet.marlam.in/dbc.php is great, thanks man. I download a db file in CSV, after edit, is there a way to convert it back to db2?

**Comment by Luzifix** [comment]
See #99
