### ISSUE TITLE
Capatability issue with release build 28807

### ISSUE THREAD

**Issue by Rokeo** [WowDevTools/WDBXEditor#82]
It seems last existing tables format do not works anymore for 8.1.
Tried with databases from last CASC build 28807.
Last Bfa supported build in tool is: 27075

Those DB i tried:
ERROR spellrange.db2 : Unknown file type.
ERROR talent.db2 : Unknown file type.
ERROR spellmisc.db2 : Unknown file type.
ERROR spellcooldowns.db2 : Unknown file type.
ERROR spellcategories.db2 : Unknown file type.
ERROR spellcategory.db2 : Unknown file type.
ERROR factiontemplate.db2 : Unknown file type.

So, i pretty sure, it is issue with reading in general, than format for some specific DB changed.

**Comment by DatTrollMon** [comment]
Yes, it is very unfortunate. Its such an amazing tool and I really hope the definition will be updated soon...

**Comment by plastid** [comment]
Starting with version 28048, the base structure is WDC3.
Of course, it is not yet supported here. But about this structure, there is information on wowdev.wiki/DB2
I did not work on C # and did not work with binary data. I will try to do something :)

**Comment by Luzifix** [comment]
See #99
