### ISSUE TITLE
Any chance update for wow 8.1?

### ISSUE THREAD

**Issue by greenonion0** [WowDevTools/WDBXEditor#86]
Its been great ever since the db2 thing comes out, appreciate, thanks for all your work.

**Comment by DatTrollMon** [comment]
> Its been great ever since the db2 thing comes out, appreciate, thanks for all your work.

I've been trying to update it myself lol, no luck. I really cant wait until the updated 8.1 definition because I was having so much fun!

**Comment by Luzifix** [comment]
see #99
